# Generated by Django 4.0.4 on 2022-05-28 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_title', models.CharField(max_length=20)),
                ('animal_type', models.CharField(choices=[('dog', 'dog'), ('cat', 'cat'), ('other', 'other pets')], max_length=10)),
                ('animal_description', models.CharField(max_length=1000)),
                ('animal_label', models.CharField(choices=[('puppy', 'puppy'), ('kitten', 'kitten'), ('small size', 'small size'), ('medium size', 'medium size'), ('high size', 'high size'), ('vaccine', 'vaccine'), ('sterilized', 'sterilized')], max_length=11)),
                ('another_label_description', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=20)),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('animal_name', models.CharField(blank=True, max_length=12, null=True)),
                ('animal_age', models.CharField(max_length=7)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('date_time', models.DateField()),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
