# Generated by Django 4.0.4 on 2022-05-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptionrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_apllicant', models.CharField(max_length=20)),
                ('email_of_the_apllicant', models.EmailField(max_length=200)),
                ('phone_number_of_the_apllicant', models.IntegerField()),
                ('district_of_the_apllicant', models.CharField(blank=True, max_length=20, null=True)),
                ('city_of_the_apllicant', models.CharField(max_length=20)),
                ('description_of_the_apllicant', models.TextField(max_length=400)),
                ('active_of_the_apllicant', models.BooleanField(default=True)),
                ('date_time_of_the_apllicant', models.DateField()),
            ],
        ),
    ]
