# Generated by Django 4.0.4 on 2022-05-29 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='date_time_of_the_apllicant',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='phone_number_of_the_apllicant',
            field=models.CharField(max_length=25),
        ),
    ]
