# Generated by Django 4.0.4 on 2022-05-29 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('adoptionrequest', '0002_alter_adoptionrequest_date_time_of_the_apllicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pets.pets'),
            preserve_default=False,
        ),
    ]
