# Generated by Django 4.0.4 on 2022-07-15 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pets_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoptionrequest', '0004_adoptionrequest_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='pet',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='pet_type',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Adoptionrequestperpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_apllicant', models.CharField(max_length=20)),
                ('email_of_the_apllicant', models.EmailField(max_length=200)),
                ('phone_number_of_the_apllicant', models.CharField(max_length=25)),
                ('district_of_the_apllicant', models.CharField(blank=True, max_length=20, null=True)),
                ('city_of_the_apllicant', models.CharField(max_length=20)),
                ('description_of_the_apllicant', models.TextField(max_length=400)),
                ('active_of_the_apllicant', models.BooleanField(default=True)),
                ('date_time_of_the_apllicant', models.DateTimeField(default=django.utils.timezone.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pets')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
