# Generated by Django 4.0.4 on 2022-08-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionrequest', '0005_remove_adoptionrequest_pet_adoptionrequest_pet_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequestperpet',
            name='active_of_the_apllicant',
        ),
        migrations.RemoveField(
            model_name='adoptionrequestperpet',
            name='city_of_the_apllicant',
        ),
        migrations.RemoveField(
            model_name='adoptionrequestperpet',
            name='district_of_the_apllicant',
        ),
    ]
